= Couplement Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2025-02-24

// This file is part of
// Couplement Forth
// (http://programandala.net/en.program.couplement_forth.html),
// by Marcos Cruz (programandala.net), 2015, 2016, 2020, 2023, 2025.
//
// This file is written in Asciidoctor format
// (http://asciidoctor.org).

== Description

Couplement Forth is a small and experimental STC (Subroutine-Threaded
Code) Forth system under development for ZX Spectrum, with a BASIC
file interface easy to adapt to any DOS.

- Home page: http://programandala.net/en.program.couplement_forth.html
- SourceHut: https://hg.sr.ht/~programandala_net/couplement_forth
- GitHub mirror: http://github.com/programandala-net/couplement-forth

== Origin

Couplement Forth was forked on 2014-12-30 from
http://programandala.net/en.program.forthcoupe.html[ForthCoupe], an
abandoned project based on John A. Avis'
http://programandala.net/en.program.samforth.html[SamForth] .

== Name

“Couplement” resembles first to the SAM Coupé origin of this Forth
system, and the combination of the original source with the ZX
Spectrum operating system; and second, it resembles to the file
interface combination with BASIC.

Besides, I found the following quote in the “couplement” entry of _The
Collaborative International Dictionary of English v.0.48 [gcide]_,
which was definitive for choosing the name:

[quote,Spenser]
____
And forth together rode, a goodly couplement.
____

== Status

Couplement Forth is usable, but many common words and are still
missing, and there's no disk support yet: the only input is the
keyboard.

Most ideas noted for Couplement Forth have already been implemented in
http://programandala.net/en.program.solo_forth.html[Solo Forth], a DTC
(Direct-Threaded Code) Forth system under active development for ZX
Spectrum 128 with G+DOS, +3DOS or TR-DOS, with a huge library.

Couplement Forth will evolve slowly, as a test system to try and
benchmark a subroutine-threaded Forth in the Z80 processor.

// The next goal is to adapt the G+DOS disk support from Solo Forth to
// Couplement Forth, which should be very easy, either natively or with
// the planned BASIC interface.  Most high-level words of the Solo Forth
// library will be compatible. Then STC-DTC comparison benchmarks will be
// possible.

// == Usage

// A TAP file is included in the bin directory. Open it with your
// favorite ZX Spectrum emulator.

== Compilation

A Makefile is provided. The only requirement is the
http://pasmo.speccy.org/[Pasmo assembler]. Do `make` and a TAP file
will be created in the <bin> directory.

== History of the repository

- 2016-03-12: A Git repository was created out of the development
  backups, in order to make future development easier and preserve the
  evolution of the code.

- 2020-12-06: The Git repository was converted to
  https://fossil-scm.org[Fossil], keeping
  http://github.com/programandala-net/couplement-forth[GitHub] as a
  mirror.

- 2023-04-05: The repository was converted
  https://mercurial-scm.org[Mercurial], enabling a better interaction
  with GitHub.

- 2024-08-04: The repository was uploaded to
  https://hg.sr.ht/~programandala_net/couplement_forth/[SourceHut].
