= Couplement Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2020-05-27

// This file is part of
// Couplement Forth
// (http://programandala.net/en.program.couplement_forth.html),
// by Marcos Cruz (programandala.net), 2015, 2016, 2020.
//
// This file is written in Asciidoctor format
// (http://asciidoctor.org).

== Description

Couplement Forth is a small and experimental STC (Subroutine-Threaded
Code) Forth system under development for ZX Spectrum, with a BASIC
file interface easy to adapt to any DOS.

Home page: http://programandala.net/en.program.couplement_forth.html

== Origin

Couplement Forth was forked on 2014-12-30 from
http://programandala.net/en.program.forthcoupe.html[ForthCoupe], an
abandoned project based on John A. Avis'
http://programandala.net/en.program.samforth.html[SamForth] .

== Name

“Couplement” resembles first to the SAM Coupé origin of this Forth
system, and the combination of the original source with the ZX
Spectrum operating system; and second, it resembles to the file
interface combination with BASIC.

Besides, I found the following quote in the “couplement” entry of _The
Collaborative International Dictionary of English v.0.48 [gcide]_,
which was definitive for choosing the name:

[quote,Spenser]
____
And forth together rode, a goodly couplement.
____

== Status

Couplement Forth is usable, but many common words and are still
missing, and there's no disk support yet: the only input is the
keyboard.

A Git repository was created on 2016-03-12 from the development
backups, in order to make future development easier and preserve the
evolution of the code.

Most ideas noted for Couplement Forth have already been implemented in
http://programandala.net/en.program.solo_forth.html[Solo Forth], a DTC
(Direct-Threaded Code) Forth system under active development for ZX
Spectrum 128 with G+DOS, +3DOS or TR-DOS, with a huge library.

== Future

Couplement Forth will evolve slowly, as a test system to try and
benchmark a subroutine-threaded Forth in the Z80 processor.

// The next goal is to adapt the G+DOS disk support from Solo Forth to
// Couplement Forth, which should be very easy, either natively or with
// the planned BASIC interface.  Most high-level words of the Solo Forth
// library will be compatible. Then STC-DTC comparison benchmarks will be
// possible.

// == Usage

// A TAP file is included in the bin directory. Open it with your
// favorite ZX Spectrum emulator.

== Compilation

A Makefile is provided. The only requirement is the
http://pasmo.speccy.org/[Pasmo assembler]. Do `make` and a TAP file
will be created in the <bin> directory.
