= Couplement Forth TO-DO
:author: Marcos Cruz (programandala.net)
:revdate: 2020-05-28

// This file is part of
// Couplement Forth
// (http://programandala.net/en.program.couplement_forth.html),
// by Marcos Cruz (programandala.net), 2015, 2016, 2020.
//
// This file is written in Asciidoctor format
// (http://asciidoctor.org).

Fix: `;` can be interpreted, even after adding `or compile_only` to
its header!

Fix: "Esc" can break the program when printing.

2015-01-11: configurable size optimization (JR/JP) and:

----
if size_optimization
 jp push_l
else
 ld h,0
 jp push_hl
endif
----

2015-01-10: key translation table to associate key codes to chars. 

2015-01-09: Investigate why `dubflag_fvar` requires a 0x01, not simply
`<>0`.  If `and a` is used instead of `cp 0x01`, the "stack empty" error
happens while compiling a number.

New: `allocate`, `free`, `resize`.

Complete the empty stack comments.

- Implement the SAM Coupé's cursors.

Convert the `create_header` routine to the new header format.

Dictionary headers in a RAM page?

Idea: `lower` and `upper` for chars, `lowers` and `uppers` for strings.

Own printing routine (from my charset224 for ZX BASIC).

Configurable "scroll?" message and behaviour: break it or not with some key.

Change the dictionary header format?

Check the compile-only checks.

Implement `pop_de` routine (useful for `>r`) and other cases marked in
the code

Try `number`.

Benchmark the data stack code.

Move all vars into the code, to save space and time.  Choose the point
where the variable is fetch more often.

Standard error numbers.

Make links point to count byte, to make vocabulary searching faster.

Change conditional relative jumps to absolute jumps,
depending on how often the condition is true.

Optimize the primitives, e.g.:
Don't use `call pad_` but take the pad address directly,
*without using the data stack*.

New words: `?do`, `case`, `?dup`.

New words: `cmove>` y `move`.

Ideas for the file interface:

- `load` to load a (already opened?) source file.
- `emit` is defered and pointed to a file when needed.
- `cr` and `type` are defered and use `emit` by default.
- `page` does `cls` on screen, but prints a form feed char to printer
  or file. Gforth and lina work this way (confirm).
- `open` and `close` manage the files (they parse the names)
- `opened` and `closed` are the non-parsing versions.
- `include` would be just `open throw load`
- Only the input word is missing. Use `key` or `accept`?

This way, all input and output could be redirected to files.

Document the stack notation.

Jumps are being adapted: Since memory is not a constraint, absolute
jumps are used where speed is important. Relative jumps are used
otherwise (e.g.  keyboard input, printing, etc.). The conditional
jumps have different timings depending on the result of the condition.
This adaptation is a work in progress.

----
;  timing of alternatives in T Cycles:
;
;  jp nz,unstructured_error   ; error: 10; no error: 01
;  ret                        ; error: 00; no error: 10
;
;  ret z                      ; error: 05; no error: 11
;  jp unstructured_error      ; error: 10; no error: 00
----

2020-05-27: Try a new data stack using `ix` as permanent pointer. Now
`drop` does `jp pop_hl` (3 bytes). Using `ix` it would do much faster
`inc ix: inc ix: ret` (5 bytes).

2020-05-27: Make the data stack grow from low memory to high memory,
towards the return stack. This makes the space between both stacks
shared. 

2020-05-27: Remove all of the compilation security checks and the
`structured` subroutine. Replace them with the method used by Solo
Forth: `csp`, `!csp` and `?csp`.

2020-05-27: Fix: any number of "?" characteres is ignored on the
command line.

2020-05-27: Fix: immediate and compile-only words can be executed in
interpretation mode. non-immediate and compile-only words (e.g.
`<builds`) don't. Probably there's a problem in `interpret`.

2020-05-27: Fix: check the data stack in `interpret` with `?stack`.

2020-05-28: Convert 0x80-terminated strings to counted strings.

2020-05-28: Remove error messages. Make error handling standard.

2020-05-28: Rewrite everything related to parsing. Make it standard.

2020-05-28: Replace inner variable `etib_fvar` with standard `>in`.

2020-05-28: Fix "[" and "]" cannot be typed.

2020-05-28: Remove routines: save_dictionary_pointers and
restore_dictionary_pointers.

2020-05-28: Fix `.` (negative numbers are not right), `u.`... Rewrite
everything after a standard factoring, like Solo Forth.

2020-05-28: Make `dp` a variable and update `here`.

2020-05-28: Rename `push_hl` routine to `hl_to_stack`, `pop_hl` to
`stack_to_hl` (`hl_from_stack`?), `push_hl_de` to `hlde_to_stack`,
etc. This seems a clearer notation in an assembly context. The words
that return their addresses can be renamed to `hl>stack`, `stack>hl`,
etc.

2020-05-28: Write `pop_ae_and_test` to factor `0exit` and `?exit`.
